In [1]:
import sys


import pandas as pd
import os
import getpass
from sqlalchemy import create_engine, text
import kagglehub
import shutil
import json

import zipfile

from pathlib import Path
from sqlalchemy.engine import URL


sys.path.append(str(Path().resolve().parents[0]))
#Local src
from src.create_database import create_database
from src.clean_column_names import clean_column_names
from src.data_validator import DataValidator



print('Done')

Done

In [2]:
cache_path = kagglehub.dataset_download("mashlyn/online-retail-ii-uci", force_download=True)

project_dir = "../data/01_raw"
os.makedirs(project_dir, exist_ok=True)

if cache_path.endswith(".zip"):
    with zipfile.ZipFile(cache_path, 'r') as z:
        z.extractall(project_dir)
    print("Extracted to:", project_dir)
else:
    for filename in os.listdir(cache_path):
        shutil.copy(os.path.join(cache_path, filename), project_dir)
    print("Copied to:", project_dir)

Downloading to /home/zxrcodev/.cache/kagglehub/datasets/mashlyn/online-retail-ii-uci/3.archive...

100%|██████████| 14.5M/14.5M [00:03<00:00, 3.84MB/s]

Extracting files...

Copied to: ../data/01_raw

In [3]:
path_csv = '../data/01_raw/online_retail_II.csv'
df = pd.read_csv(path_csv)
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [4]:
print(df.columns)
print(df.info())
print(df.describe(include='all'))

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB
None
        Invoice StockCode                         Description      Quantity  \
count   1067371   1067371                             1062989  1.067371e+06
unique    53628      5305                                5698           NaN
top      537434    85123A  WHITE HANGING HEART T-LIGHT HOLDER           NaN
freq       1350      5829                                5918           NaN
mean        NaN       NaN                                 NaN  9.938898e+00
std         NaN       NaN                                 NaN  1.727058e+02
min         NaN       NaN                                 NaN -8.099500e+04
25%         NaN       NaN                                 NaN  1.000000e+00
50%         NaN       NaN                                 NaN  3.000000e+00
75%         NaN       NaN                                 NaN  1.000000e+01
max         NaN       NaN                                 NaN  8.099500e+04

                InvoiceDate         Price    Customer ID         Country
count               1067371  1.067371e+06  824364.000000         1067371
unique                47635           NaN            NaN              43
top     2010-12-06 16:57:00           NaN            NaN  United Kingdom
freq                   1350           NaN            NaN          981330
mean                    NaN  4.649388e+00   15324.638504             NaN
std                     NaN  1.235531e+02    1697.464450             NaN
min                     NaN -5.359436e+04   12346.000000             NaN
25%                     NaN  1.250000e+00   13975.000000             NaN
50%                     NaN  2.100000e+00   15255.000000             NaN
75%                     NaN  4.150000e+00   16797.000000             NaN
max                     NaN  3.897000e+04   18287.000000             NaN

- It shows that price and quantity takes minus values in the dataset; 
- the column customer_id is float;

In [5]:
df = clean_column_names(df)
df.columns

Index(['invoice', 'stock_code', 'description', 'quantity', 'invoice_date',
       'price', 'customer_id', 'country'],
      dtype='object')

In [6]:
report = DataValidator.validate(df)

print(json.dumps(report, indent=2))

{
  "missing": {
    "rows": 1067371,
    "columns": 8,
    "per_column": {
      "invoice": {
        "missing_count": 0,
        "missing_pct": 0.0
      },
      "stock_code": {
        "missing_count": 0,
        "missing_pct": 0.0
      },
      "description": {
        "missing_count": 4382,
        "missing_pct": 0.0041054141437232225
      },
      "quantity": {
        "missing_count": 0,
        "missing_pct": 0.0
      },
      "invoice_date": {
        "missing_count": 0,
        "missing_pct": 0.0
      },
      "price": {
        "missing_count": 0,
        "missing_pct": 0.0
      },
      "customer_id": {
        "missing_count": 243007,
        "missing_pct": 0.22766872999172733
      },
      "country": {
        "missing_count": 0,
        "missing_pct": 0.0
      }
    }
  },
  "duplicates": {
    "duplicate_count": 34335,
    "sample_rows": [
      {
        "invoice": "489517",
        "stock_code": "21912",
        "description": "VINTAGE SNAKES & LADDERS",
        "quantity": 1,
        "invoice_date": "2009-12-01 11:34:00",
        "price": 3.75,
        "customer_id": 16329.0,
        "country": "United Kingdom"
      },
      {
        "invoice": "489517",
        "stock_code": "22130",
        "description": "PARTY CONE CHRISTMAS DECORATION ",
        "quantity": 6,
        "invoice_date": "2009-12-01 11:34:00",
        "price": 0.85,
        "customer_id": 16329.0,
        "country": "United Kingdom"
      },
      {
        "invoice": "489517",
        "stock_code": "22319",
        "description": "HAIRCLIPS FORTIES FABRIC ASSORTED",
        "quantity": 12,
        "invoice_date": "2009-12-01 11:34:00",
        "price": 0.65,
        "customer_id": 16329.0,
        "country": "United Kingdom"
      },
      {
        "invoice": "489517",
        "stock_code": "21913",
        "description": "VINTAGE SEASIDE JIGSAW PUZZLES",
        "quantity": 1,
        "invoice_date": "2009-12-01 11:34:00",
        "price": 3.75,
        "customer_id": 16329.0,
        "country": "United Kingdom"
      },
      {
        "invoice": "489517",
        "stock_code": "21821",
        "description": "GLITTER STAR GARLAND WITH BELLS ",
        "quantity": 1,
        "invoice_date": "2009-12-01 11:34:00",
        "price": 3.75,
        "customer_id": 16329.0,
        "country": "United Kingdom"
      }
    ]
  },
  "dtypes": {
    "actual_dtypes": {
      "invoice": "object",
      "stock_code": "object",
      "description": "object",
      "quantity": "int64",
      "invoice_date": "object",
      "price": "float64",
      "customer_id": "float64",
      "country": "object"
    },
    "dtype_mismatches": {}
  },
  "cardinality": {
    "invoice": {
      "unique": 53628,
      "top_values": {
        "537434": 1350,
        "538071": 1304,
        "537638": 1202,
        "537237": 1194,
        "536876": 1186
      }
    },
    "stock_code": {
      "unique": 5305,
      "top_values": {
        "85123A": 5829,
        "22423": 4424,
        "85099B": 4216,
        "21212": 3318,
        "20725": 3259
      }
    },
    "description": {
      "unique": 5699,
      "top_values": {
        "WHITE HANGING HEART T-LIGHT HOLDER": 5918,
        "REGENCY CAKESTAND 3 TIER": 4412,
        "NaN": 4382,
        "JUMBO BAG RED RETROSPOT": 3469,
        "ASSORTED COLOUR BIRD ORNAMENT": 2958
      }
    },
    "quantity": {
      "unique": 1057,
      "top_values": {
        "1": 294346,
        "2": 159960,
        "12": 121745,
        "6": 85299,
        "3": 72638
      }
    },
    "invoice_date": {
      "unique": 47635,
      "top_values": {
        "2010-12-06 16:57:00": 1350,
        "2010-12-09 14:09:00": 1304,
        "2010-12-07 15:28:00": 1202,
        "2010-12-06 09:58:00": 1194,
        "2010-12-03 11:36:00": 1186
      }
    },
    "price": {
      "unique": 2807,
      "top_values": {
        "1.25": 104428,
        "1.65": 73808,
        "0.85": 69218,
        "2.95": 65862,
        "0.42": 45438
      }
    },
    "customer_id": {
      "unique": 5943,
      "top_values": {
        "NaN": 243007,
        "17841.0": 13097,
        "14911.0": 11613,
        "12748.0": 7307,
        "14606.0": 6709
      }
    },
    "country": {
      "unique": 43,
      "top_values": {
        "United Kingdom": 981330,
        "EIRE": 17866,
        "Germany": 17624,
        "France": 14330,
        "Netherlands": 5140
      }
    }
  },
  "outliers": {
    "quantity": {
      "n": 1067371,
      "low_bound": -12.5,
      "high_bound": 23.5,
      "below": 4459,
      "above": 112030
    },
    "price": {
      "n": 1067371,
      "low_bound": -3.1000000000000005,
      "high_bound": 8.5,
      "below": 5,
      "above": 68100
    },
    "customer_id": {
      "n": 824364,
      "low_bound": 9742.0,
      "high_bound": 21030.0,
      "below": 0,
      "above": 0
    }
  }
}

- approx 23% of missing customer IDs;
- 0.4% of missing descriptions; 
- 34k of duplicates;

In [7]:
print(df.loc[df['quantity'] < 0].shape)
print(df.loc[df['quantity'] == 0].shape)
print(df.loc[df['price'] < 0].shape)
print(df.loc[df['price'] == 0].shape)

(22950, 8)
(0, 8)
(5, 8)
(6202, 8)

- 23k of entries where quantity is negative; # either issues or refunds
- 6k of entries where price is negative; # probably issues

In [8]:
df.loc[df['quantity'] < 0, :]

,invoice,stock_code,description,quantity,invoice_date,price,customer_id,country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
...,...,...,...,...,...,...,...,...
1065910,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
1067002,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
1067176,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
1067177,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
1067178,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [9]:
df.loc[(df['invoice'].str.startswith('C', na=False)) & (df['quantity'] > 0)].index

Index([76799], dtype='int64')

- invoice starts with C in quantity < 0, can be mark of cancellation;
- only one entry with C that has positive quantity;

In [10]:
df[df.duplicated(keep=False)].sort_values(by=list(df.columns))

,invoice,stock_code,description,quantity,invoice_date,price,customer_id,country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
...,...,...,...,...,...,...,...,...
965610,C574510,22360,GLASS JAR ENGLISH CONFECTIONERY,-1,2011-11-04 13:25:00,2.95,15110.0,United Kingdom
986868,C575940,23309,SET OF 60 I LOVE LONDON CAKE CASES,-24,2011-11-13 11:38:00,0.55,17838.0,United Kingdom
986869,C575940,23309,SET OF 60 I LOVE LONDON CAKE CASES,-24,2011-11-13 11:38:00,0.55,17838.0,United Kingdom
1055441,C580764,22667,RECIPE BOX RETROSPOT,-12,2011-12-06 10:38:00,2.95,14562.0,United Kingdom
1055442,C580764,22667,RECIPE BOX RETROSPOT,-12,2011-12-06 10:38:00,2.95,14562.0,United Kingdom

- duplicates can be due to logging issues.

In [11]:
df = df.dropna(subset=['customer_id']).copy()
df['customer_id'] = df['customer_id'].astype(int)
#df = df[df['quantity'] > 0].copy()
df = df[df['price'] != 0].copy()
df = df[df['price'] > 0].copy()
df = df.drop(df.loc[(df['invoice'].str.startswith('C', na=False)) & (df['quantity'] > 0)].index).copy()
df['invoice_date'] = pd.to_datetime(df['invoice_date'])
df['description'] = df['description'].str.strip()
df = df.drop_duplicates().copy()

- dropped empty customer_id columns, as they cannot be filled;
- converted customer_id column type to int for sql loading;
- converted invoice_date column type to datetime for plotting.
- dropped negative and zero values from price column;
- dropped duplicates, as they are probably system log issues;

In [12]:
tmp = df.sort_values(by='price', ascending=False)
print(tmp['description'].head(5000).unique().tolist())
print(tmp['stock_code'].head(5000).unique().tolist())

['Manual', 'POSTAGE', 'Discount', 'DOTCOM POSTAGE', 'CRUK Commission', 'PICNIC BASKET WICKER 60 PIECES', 'Adjustment by john on 26/01/2010 17', 'Adjustment by Peter on 24/05/2010 1', 'Adjustment by Peter on Jun 25 2010', 'Adjustment by john on 26/01/2010 16', 'VINTAGE BLUE KITCHEN CABINET', 'VINTAGE RED KITCHEN CABINET', 'LOVE SEAT ANTIQUE WHITE METAL', 'RUSTIC  SEVENTEEN DRAWER SIDEBOARD', 'REGENCY MIRROR WITH SHUTTERS', 'GIANT SEVENTEEN DRAWER SIDEBOARD', 'CARRIAGE', 'BLUE KASHMIRI COFFEE TABLE', 'CHEST NATURAL WOOD 20 DRAWERS', 'FRENCH STYLE WALL DRESSER', 'ANT WHITE SWEETHEART TABLE W 3 DRAW', 'VINTAGE POST OFFICE CABINET', 'BLUE KASHMIRI OCCASIONAL TABLE', 'PINK KASHMIRI OCCASIONAL TABLE', 'GREEN KASHMIRI OCCASIONAL TABLE', 'SCHOOL DESK AND CHAIR', 'PINK KASHMIRI COFFEE TABLE', 'PINK PAINTED KASHMIRI TABLE', 'BLUE PAINTED KASHMIRI TABLE', 'DECORATIVE HANGING SHELVING UNIT', 'SET/3 COLOUR PAINTED KASHMIRI STOOL', 'BROCADE RING PURSE', 'HALL CABINET WITH 3 DRAWERS', 'BLUE PAINTED KASHMIRI CHAIR', 'METAL WALL SHELF UNIT WITH HOOKS', 'CINDERELLA CHANDELIER', 'PINK PAINTED KASHMIRI CHAIR', 'SHAKER THROW  QUILTED', 'ANTIQUE EDWARDIAN DRESSER', 'PINK AND LILAC QUILTED THROW', 'BLUE GINGHAM ROSE QUILT', 'GREEN ROSE QUILT', 'PINK PAISLEY QUILT', 'CANDY STRIPE ROSE QUILT', 'Bank Charges', 'DANISH ROSE BEDSIDE CABINET', 'SET/4 WHITE RETRO STORAGE CUBES', 'BLUE RETRO BAR STOOL', 'IVORY EMBROIDERED QUILT', 'MEDINA STAMPED METAL STOOL', 'VINTAGE WOODEN PLATE RACK', 'ENGLISH ROSE DESIGN QUILTED THROW', 'BLACK RETRO BAR STOOL', 'DANISH ROSE FOLDING CHAIR', 'FUSCHIA RETRO BAR STOOL', 'RED RETRO BAR STOOL', 'PADS TO MATCH ALL CUSHIONS', 'EDWARDIAN 2 DRAWER WALL CABINET', '3 TIER SWEETHEART GARDEN SHELF', 'BREAD BIN DINER STYLE IVORY', 'CHEST OF DRAWERS GINGHAM HEART', 'Next Day Carriage', 'VINTAGE WOODEN BAR STOOL', 'CABIN BAG VINTAGE PAISLEY', 'CABIN BAG VINTAGE RETROSPOT', 'WOOD AND GLASS MEDICINE CABINET', 'SILVER ROCCOCO CHANDELIER', 'CAPIZ CHANDELIER', 'FRENCH STYLE WIRE DOOR CABINET', '3 TIER CAKE TIN RED AND CREAM', '3 TIER CAKE TIN GREEN AND CREAM', 'UTILTY CABINET WITH HOOKS', 'PINK ROSE PICNIC RUG', 'SQUARE CHERRY BLOSSOM CABINET', 'BOTANICAL GARDENS WALL CLOCK', 'REGENCY CAKESTAND 3 TIER', 'VICTORIAN SEWING BOX LARGE', 'ENAMEL BREAD BIN CREAM', 'WOODEN CROQUET GARDEN SET', '12 EGG HOUSE PAINTED WOOD', 'CLASSIC METAL BIRDCAGE PLANT HOLDER', 'BOX OF VINTAGE ALPHABET BLOCKS', 'SET OF 16 VINTAGE RED CUTLERY', 'SET OF 4 DIAMOND NAPKIN RINGS', 'CREAM SWEETHEART MINI CHEST', 'SET OF 16 VINTAGE BLACK CUTLERY', 'SET 3 WICKER STORAGE BASKETS', 'RUSTIC WOODEN CABINET, GLASS DOORS', 'CHALKBOARD KITCHEN ORGANISER', 'CHEST 7 DRAWER MA CAMPAGNE', 'SET OF 3 WICKER BASKET ROSE', 'SET OF 3 WICKER BASKET TEA AND CAKE', 'FRENCH STYLE EMBOSSED HEART CABINET', 'LIBRARY LAMP', 'WHITE 3 FRAME BIRDS AND TREE', 'High Resolution Image', 'PINK KASHMIRI BOXED MIRROR', 'BLUE KASHMIRI BOXED MIRROR', 'SILVER JEWELLED MIRROR TRINKET TRAY', 'REGENCY TEAPOT ROSES', 'FAMILY PHOTO FRAME CORNICE', 'PINK JEWELLED MIRROR TRINKET TRAY', 'NOVELTY BISCUITS CAKE STAND 3 TIER', 'WHITE WOOD GARDEN PLANT LADDER', 'SWEETHEART CREAM STEEL FOLDIN BENCH', 'FAUX FUR CHOCOLATE THROW', 'SET 3 WICKER LOG BASKETS', 'SWEETHEART CREAM STEEL TABLE RECT', 'ROCOCO WALL MIRROR WHITE', 'SET 3 WICKER OVAL BASKETS W LIDS', 'MARAKESH LANTERN LARGE', 'ROCOCO WALL MIROR', 'BIG PINK POODLE', 'CLASSICAL ROSE TABLE LAMP', 'MIRROR, ARCHED GEORGIAN', 'CREAM SWEETHEART WALL CABINET', 'ACRYLIC GEOMETRIC LAMP', 'FUSCHIA/GREEN STRIPE WOOLLY BLANKET', 'CERAMIC CHERRY CAKE MONEY BANK', 'BREAD BIN DINER STYLE MINT', 'BREAD BIN DINER STYLE RED', 'BREAD BIN DINER STYLE PINK', 'SEWING BOX RETROSPOT DESIGN', 'GLASS CAKE COVER AND PLATE', 'WOODEN ADVENT CALENDAR RED', 'WOODEN ADVENT CALENDAR CREAM', 'SILVER CHRISTMAS TREE BAUBLE STAND', 'SUNSET COLOUR CHUNKY KNITTED THROW', 'CREAM SWEETHEART MAGAZINE RACK', 'SPACEBOY BABY GIFT SET', 'WHITE GOOSE FEATHER CHRISTMAS TREE', 'GREEN GOOSE FEATHER CHRISTMAS TREE', 'DOLLY GIRL BABY GIFT SET', 'BLUE SAVANNAH PICNIC HAMPER FOR 4', 'PINK HAWAIIAN PICNIC HAMPER FOR 4', 'I LOVE LONDON BABY GIFT SET', 'ZINC TOP  2 DOOR WOODEN SHELF', 'FILIGREE WALL MIRROR  ANTIQUE WHITE', 'CIRCUS PARADE BABY GIFT SET', 'FUNKY FLOWER PICNIC BAG FOR 4', 'TEATIME FUNKY FLOWER BACKPACK FOR 2', 'RIDGED GLASS PENDANT LAMPSHADE', 'LARGE ENGLISH ARBORETUM', 'CANDY POP CHUNKY KNITTED THROW', 'BUBBLE GUM CHUNKY KNITTED THROW']
['M', 'POST', 'D', 'DOT', 'CRUK', '22502', 'ADJUST', 'ADJUST2', '22656', '22655', '22826', '22827', '22828', 'C2', '84965B', '22823', '21760', '85070', '21769', '84967B', '84967A', '84967C', '22929', '84965A', '84964A', '84964B', '84632', '84962', '17003', '22833', '84963B', '21759', '23064', '84963A', '20833', '21300', '84472', '84619', '84653', '84909A', '84626', 'BANK CHARGES', '84816', '84078A', '20787', '22803', '21686', '21764', '84467', '20786', '84823', '20785', '20784', 'PADS', '21298', '22824', '22847', '22797', '23444', '21763', '22503', '22504', '21761', '84616', '21310', '21767', '22838', '22839', '22830', '84914A', '84665', '23485', '22423', '21258', '22424', '22605', '22282', '21340', '22622', '84968D', '84813', '85066', '84968E', '22782', '22764', '22769', '22761', '47583A', '47583B', '21277', '21335', '84629', '23702', '84966A', '84966B', '84707A', '23173', '22768', '84707B', '22890', '22487', '21474', '22802', '21737', '21473', '23462', '22783', '21339', '84371', '84679', '22790', '85067', '85161', '84414B', '22644', '22849', '22846', '22848', '22509', '21667', '22947', '22946', '84352', '46775D', '85063', '23007', '21262', '21261', '23008', '84797B', '84797A', '23009', '21275', '21303', '23010', '84873A', '84872A', '21674', '84830', '46775E', '46775A']

In [13]:
df[df['stock_code'] == 'C2']

,invoice,stock_code,description,quantity,invoice_date,price,customer_id,country
9292,490127,C2,CARRIAGE,1,2009-12-03 18:13:00,50.0,14156,EIRE
14502,490542,C2,CARRIAGE,1,2009-12-07 09:42:00,50.0,14911,EIRE
19541,490998,C2,CARRIAGE,1,2009-12-08 17:24:00,50.0,16253,United Kingdom
22803,491160,C2,CARRIAGE,1,2009-12-10 10:29:00,50.0,14911,EIRE
32964,492092,C2,CARRIAGE,1,2009-12-15 14:03:00,50.0,14156,EIRE
...,...,...,...,...,...,...,...,...
1038663,579539,C2,CARRIAGE,1,2011-11-30 10:06:00,50.0,14911,EIRE
1040462,579768,C2,CARRIAGE,1,2011-11-30 15:08:00,50.0,14911,EIRE
1041945,579910,C2,CARRIAGE,1,2011-12-01 08:52:00,50.0,14911,EIRE
1044366,580127,C2,CARRIAGE,1,2011-12-01 17:51:00,50.0,14911,EIRE
1049913,580555,C2,CARRIAGE,1,2011-12-05 10:18:00,50.0,14911,EIRE

- many rows with large prices are invalid, as they are not products, so it is not suitable for my calc;

In [14]:
non_product_keywords = [
    'manual', 
    'postage', 
    'dotcom postage', 
    'bank charges', 
    'amazon fee', 
    'discount', 
    'cruk commission', 
    'adjust',
    'carriage'
]

pattern = '|'.join(non_product_keywords)

df = df[~df['description'].str.lower().str.contains(pattern, na=False)].copy()

In [15]:
tmp = df.sort_values(by='quantity', ascending=False)
print(tmp[['description', 'stock_code', 'price', 'quantity']].head(50))
print(tmp[['description', 'stock_code', 'price', 'quantity']].tail(50))

                                 description stock_code  price  quantity
1065882          PAPER CRAFT , LITTLE BIRDIE      23843   2.08     80995
587080        MEDIUM CERAMIC TOP STORAGE JAR      23166   1.04     74215
90857     BLACK AND WHITE PAISLEY FLOWER MUG      37410   0.10     19152
127168           SET/6 WOODLAND PAPER PLATES      21091   0.10     12960
127166           SET/6 STRAWBERRY PAPER CUPS      21099   0.10     12960
127169             SET/6 WOODLAND PAPER CUPS      21085   0.10     12744
127167         SET/6 STRAWBERRY PAPER PLATES      21092   0.10     12480
135027       PACK OF 12 PINK PAISLEY TISSUES      21984   0.25     10000
135029         PACK OF 12 RED SPOTTY TISSUES      21980   0.25     10000
135028               PACK OF 12 SUKI TISSUES      21982   0.25     10000
135030           PACK OF 12 WOODLAND TISSUES      21981   0.25     10000
93677        SMALL FAIRY CAKE FRIDGE MAGNETS      85220   0.30      9456
432176   ROTATING SILVER ANGELS T-LIGHT HLDR      84347   1.69      9360
65091                   JAZZ HEARTS MEMO PAD      20993   0.10      9312
326847                    BROCADE RING PURSE      17003   0.19      7128
298942          SET/6 FRUIT SALAD PAPER CUPS      21088   0.08      7128
358764          SET/6 FRUIT SALAD PAPER CUPS      21088   0.08      7128
358763       SET/6 FRUIT SALAD  PAPER PLATES      21096   0.13      7008
298941       SET/6 FRUIT SALAD  PAPER PLATES      21096   0.13      7008
65090          JAZZ HEARTS MAGNETIC MEMO PAD      20991   0.10      6768
90866              ASS FLORAL PRINT SCISSORS     47503E   0.15      6696
432177                    BROCADE RING PURSE      17003   0.19      6336
65079               POP-ART FLUORESCENT PENS      16044   0.06      6144
65077     BLACK AND WHITE PAISLEY FLOWER MUG      37410   0.10      6012
127172                     ORANGE FLOWER MUG      37351   0.10      5364
65088                 GREEN FERN POCKET BOOK      20756   0.10      5280
65085              CHRYSANTHEMUM POCKET BOOK      20759   0.10      5280
298953               POP ART PEN CASE & PENS      16047   0.08      5184
358774               POP ART PEN CASE & PENS      16047   0.08      5184
7303                PACK OF 12 SKULL TISSUES      21967   0.25      5184
201394               PACK OF 12 SUKI TISSUES      21982   0.50      5000
201392      PACK OF 12 HEARTS DESIGN TISSUES      21985   0.50      5000
358755         MULTICOLOUR SPRING FLOWER MUG      37340   0.10      4992
298933         MULTICOLOUR SPRING FLOWER MUG      37340   0.10      4992
65087                  RED DAISY POCKET BOOK      20757   0.10      4800
947093     WORLD WAR 2 GLIDERS ASSTD DESIGNS      84077   0.21      4800
65086           ABSTRACT CIRCLES POCKET BOOK      20758   0.10      4800
358738    BLACK SILVER FLOWER T-LIGHT HOLDER      85110   0.07      4752
298916    BLACK SILVER FLOWER T-LIGHT HOLDER      85110   0.07      4752
379876                    BROCADE RING PURSE      17003   0.19      4752
127171                      BIRD IN TREE MUG      37352   0.10      4608
358775               TEATIME PEN CASE & PENS      16046   0.08      4608
298954               TEATIME PEN CASE & PENS      16046   0.08      4608
65089               BLUE PAISLEY POCKET BOOK      20755   0.10      4320
90882                GARDEN PATH POCKET BOOK      20760   0.10      4320
298915          WHITE BIRD GARDEN DESIGN MUG     85160A   0.13      4320
358737          WHITE BIRD GARDEN DESIGN MUG     85160A   0.13      4320
432173     WORLD WAR 2 GLIDERS ASSTD DESIGNS      84077   0.18      4320
7302             PACK OF 12 WOODLAND TISSUES      21981   0.25      4320
731582                  SMALL POPCORN HOLDER      22197   0.72      4300
                                 description stock_code  price  quantity
359641         PINK BREAKFAST CUP AND SAUCER     37444C   0.13      -768
829883                   HOME SWEET HOME MUG      21877   1.06      -828
225541                    LUNCH BAG WOODLAND      20726   1.45      -830
225543                   LUNCH BAG CARS BLUE      20728   1.45      -830
225542               LUNCH BAG  BLACK SKULL.      20727   1.45      -830
916004            FELTCRAFT BUTTERFLY HEARTS      22147   1.25      -840
359633                          GOLD WASHBAG      21336   0.13      -864
708189     WORLD WAR 2 GLIDERS ASSTD DESIGNS      84077   0.21      -960
359657              POP ART PUSH DOWN RUBBER      16043   0.06      -960
359640         BLUE BREAKFAST CUP AND SAUCER     37444B   0.13      -984
359656               ARMY CAMO WRAPPING TAPE     10123G   0.06     -1104
359645                   FLORAL BATHROOM SET      84847   0.33     -1116
418860     COLOUR GLASS. STAR T-LIGHT HOLDER      71477   2.75     -1152
359671        VINTAGE KITCHEN PRINT PUDDINGS      21278   0.25     -1200
902909            PAPER POCKET TRAVELING FAN      15034   0.07     -1200
197424               PINK FAIRY CAKE COASTER     47587A   0.72     -1200
359631      VINTAGE KITCHEN PRINT VEGETABLES      21280   0.25     -1248
916005      PINK BLUE FELT CRAFT TRINKET BOX      20971   1.06     -1296
685603                TEA TIME PARTY BUNTING     47566B   2.55     -1300
359639       YELLOW BREAKFAST CUP AND SAUCER     37444A   0.13     -1308
359651         SET 4 NURSERY DES ROUND BOXES      85006   0.31     -1440
157466          ASSTD DESIGN BUBBLE GUM RING      84270   0.16     -1440
749880                     HERB MARKER BASIL      22920   0.55     -1515
359632         VINTAGE KITCHEN PRINT SEAFOOD      21281   0.25     -1536
359672          VINTAGE KITCHEN PRINT FRUITS      21279   0.25     -1632
359652           PINK BOUDOIR T-LIGHT HOLDER      85109   0.07     -1872
685604    WHITE HANGING HEART T-LIGHT HOLDER     85123A   2.55     -1930
685605           GIN + TONIC DIET METAL SIGN      21175   1.85     -2000
359659         POPART COL BALLPOINT PEN ASST      16053   0.03     -2000
359638             WHITE WITH BLACK CATS MUG      37424   0.13     -2112
463406   ESSENTIAL BALM 3.5g TIN IN ENVELOPE      18007   0.05     -2400
359635            BLUE POLKADOT PUDDING BOWL      21393   0.13     -2496
93676        SMALL FAIRY CAKE FRIDGE MAGNETS      85220   1.45     -2504
359637           WHITE WITH BLACK CATS PLATE      37423   0.10     -2952
359673          BLACK BIRD GARDEN DESIGN MUG     85160B   0.13     -2976
359668      SET/20 FRUIT SALAD PAPER NAPKINS      21082   0.17     -3072
685606    FAIRY CAKE FLANNEL ASSORTED COLOUR      21108   2.10     -3114
359634             RED POLKADOT PUDDING BOWL      21392   0.13     -3648
359660                     THE KING GIFT BAG     16162L   0.05     -3744
359674        S/4 BLUE ROUND DECOUPAGE BOXES     85184D   0.42     -3936
359654          WHITE BIRD GARDEN DESIGN MUG     85160A   0.13     -4320
359658               TEATIME PEN CASE & PENS      16046   0.08     -4608
359653    BLACK SILVER FLOWER T-LIGHT HOLDER      85110   0.07     -4752
359636         MULTICOLOUR SPRING FLOWER MUG      37340   0.10     -4992
359630               POP ART PEN CASE & PENS      16047   0.08     -5184
359670       SET/6 FRUIT SALAD  PAPER PLATES      21096   0.13     -7008
359669          SET/6 FRUIT SALAD PAPER CUPS      21088   0.08     -7128
507225   ROTATING SILVER ANGELS T-LIGHT HLDR      84347   0.03     -9360
587085        MEDIUM CERAMIC TOP STORAGE JAR      23166   1.04    -74215
1065883          PAPER CRAFT , LITTLE BIRDIE      23843   2.08    -80995

- big quantities are valid;

In [16]:
df['revenue'] = df['quantity'] * df['price']
df.groupby('customer_id')['revenue'].sum().describe()

count      5875.000000
mean       2784.032398
std       13798.791404
min       -1343.240000
25%         328.000000
50%         835.220000
75%        2164.280000
max      578408.640000
Name: revenue, dtype: float64

- some of our customers are having negative revenue, probably data on their initial purchase was not collected, but refund was;

In [17]:
tmp = df.groupby('customer_id')['revenue'].sum().reset_index()
negative_ids = tmp['customer_id'][tmp['revenue'] < 0]
df = df[~df['customer_id'].isin(negative_ids)].copy()
df

,invoice,stock_code,description,quantity,invoice_date,price,customer_id,country,revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.40
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.00
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.00
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.80
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.00
...,...,...,...,...,...,...,...,...,...
1067365,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85

In [18]:
print(df[['country', 'revenue', 'invoice_date']].sort_values(by='invoice_date', ascending=False).head(50))
print(df[['country', 'revenue', 'invoice_date']].sort_values(by='invoice_date', ascending=False).tail(50))

                country  revenue        invoice_date
1067369          France    14.85 2011-12-09 12:50:00
1067362          France    15.60 2011-12-09 12:50:00
1067356          France    19.80 2011-12-09 12:50:00
1067357          France    19.80 2011-12-09 12:50:00
1067358          France    15.00 2011-12-09 12:50:00
1067359          France    15.00 2011-12-09 12:50:00
1067360          France    15.00 2011-12-09 12:50:00
1067361          France    15.00 2011-12-09 12:50:00
1067355          France    23.40 2011-12-09 12:50:00
1067363          France    23.40 2011-12-09 12:50:00
1067365          France    10.20 2011-12-09 12:50:00
1067366          France    12.60 2011-12-09 12:50:00
1067367          France    16.60 2011-12-09 12:50:00
1067368          France    16.60 2011-12-09 12:50:00
1067364          France    16.60 2011-12-09 12:50:00
1067353  United Kingdom   214.80 2011-12-09 12:49:00
1067352  United Kingdom    30.00 2011-12-09 12:49:00
1067351  United Kingdom    23.60 2011-12-09 12:49:00
1067354  United Kingdom    70.80 2011-12-09 12:49:00
1067340  United Kingdom    30.00 2011-12-09 12:31:00
1067330  United Kingdom     4.68 2011-12-09 12:31:00
1067331  United Kingdom     4.56 2011-12-09 12:31:00
1067332  United Kingdom    23.40 2011-12-09 12:31:00
1067333  United Kingdom    15.00 2011-12-09 12:31:00
1067334  United Kingdom    20.40 2011-12-09 12:31:00
1067335  United Kingdom    24.96 2011-12-09 12:31:00
1067336  United Kingdom    27.04 2011-12-09 12:31:00
1067337  United Kingdom    20.40 2011-12-09 12:31:00
1067338  United Kingdom    17.00 2011-12-09 12:31:00
1067339  United Kingdom    17.85 2011-12-09 12:31:00
1067349  United Kingdom    11.40 2011-12-09 12:31:00
1067341  United Kingdom    15.00 2011-12-09 12:31:00
1067342  United Kingdom     8.50 2011-12-09 12:31:00
1067343  United Kingdom    10.08 2011-12-09 12:31:00
1067344  United Kingdom    10.50 2011-12-09 12:31:00
1067345  United Kingdom    15.00 2011-12-09 12:31:00
1067346  United Kingdom    10.20 2011-12-09 12:31:00
1067347  United Kingdom     4.68 2011-12-09 12:31:00
1067348  United Kingdom    15.00 2011-12-09 12:31:00
1067350  United Kingdom    23.40 2011-12-09 12:31:00
1067329  United Kingdom    88.80 2011-12-09 12:25:00
1067328  United Kingdom    51.84 2011-12-09 12:25:00
1067327  United Kingdom    66.60 2011-12-09 12:23:00
1067326  United Kingdom    58.00 2011-12-09 12:23:00
1067324  United Kingdom    12.48 2011-12-09 12:21:00
1067325  United Kingdom    17.40 2011-12-09 12:21:00
1067304  United Kingdom     0.84 2011-12-09 12:20:00
1067310  United Kingdom     0.59 2011-12-09 12:20:00
1067297  United Kingdom    17.34 2011-12-09 12:20:00
1067298  United Kingdom    17.34 2011-12-09 12:20:00
           country  revenue        invoice_date
37  United Kingdom    13.50 2009-12-01 09:08:00
32  United Kingdom    12.60 2009-12-01 09:08:00
34  United Kingdom    13.50 2009-12-01 09:08:00
33  United Kingdom    10.20 2009-12-01 09:08:00
42  United Kingdom    15.30 2009-12-01 09:08:00
31  United Kingdom    12.60 2009-12-01 09:08:00
41  United Kingdom    10.20 2009-12-01 09:08:00
35  United Kingdom     9.95 2009-12-01 09:08:00
43  United Kingdom    12.75 2009-12-01 09:08:00
49  United Kingdom    17.70 2009-12-01 09:08:00
44  United Kingdom     7.80 2009-12-01 09:08:00
52  United Kingdom    14.85 2009-12-01 09:08:00
51  United Kingdom    15.00 2009-12-01 09:08:00
50  United Kingdom    17.70 2009-12-01 09:08:00
53  United Kingdom    14.85 2009-12-01 09:08:00
48  United Kingdom    17.70 2009-12-01 09:08:00
47  United Kingdom    15.00 2009-12-01 09:08:00
46  United Kingdom    10.20 2009-12-01 09:08:00
45  United Kingdom    10.20 2009-12-01 09:08:00
21  United Kingdom    15.00 2009-12-01 09:06:00
12  United Kingdom    59.50 2009-12-01 09:06:00
13  United Kingdom    98.10 2009-12-01 09:06:00
14  United Kingdom    17.85 2009-12-01 09:06:00
15  United Kingdom    27.04 2009-12-01 09:06:00
16  United Kingdom    20.85 2009-12-01 09:06:00
17  United Kingdom    17.40 2009-12-01 09:06:00
18  United Kingdom    19.80 2009-12-01 09:06:00
19  United Kingdom    19.80 2009-12-01 09:06:00
20  United Kingdom    54.24 2009-12-01 09:06:00
25  United Kingdom    25.20 2009-12-01 09:06:00
22  United Kingdom    17.00 2009-12-01 09:06:00
23  United Kingdom    55.80 2009-12-01 09:06:00
24  United Kingdom    25.20 2009-12-01 09:06:00
26  United Kingdom    17.85 2009-12-01 09:06:00
27  United Kingdom    17.70 2009-12-01 09:06:00
28  United Kingdom    10.00 2009-12-01 09:06:00
29  United Kingdom    10.00 2009-12-01 09:06:00
30  United Kingdom   102.00 2009-12-01 09:06:00
11  United Kingdom    30.60 2009-12-01 07:46:00
10  United Kingdom    39.60 2009-12-01 07:46:00
9   United Kingdom    45.00 2009-12-01 07:46:00
8   United Kingdom    30.60 2009-12-01 07:46:00
2   United Kingdom    81.00 2009-12-01 07:45:00
4   United Kingdom    30.00 2009-12-01 07:45:00
3   United Kingdom   100.80 2009-12-01 07:45:00
1   United Kingdom    81.00 2009-12-01 07:45:00
5   United Kingdom    39.60 2009-12-01 07:45:00
6   United Kingdom    30.00 2009-12-01 07:45:00
7   United Kingdom    59.50 2009-12-01 07:45:00
0   United Kingdom    83.40 2009-12-01 07:45:00

- the records start and end smoothly, but in Dec, right before New Year;

In [19]:
df

,invoice,stock_code,description,quantity,invoice_date,price,customer_id,country,revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.40
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.00
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.00
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.80
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.00
...,...,...,...,...,...,...,...,...,...
1067365,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85

Saving the full df for further eda:

In [20]:
pd_to_csv_path = os.path.join('..', 'data', '02_processed', 'cleaned_retail.csv')

os.makedirs(os.path.dirname(pd_to_csv_path), exist_ok=True)
df.to_csv(pd_to_csv_path, index=False)

print(f"Saved to: {pd_to_csv_path}")

Saved to: ../data/02_processed/cleaned_retail.csv

In [21]:
db_name = input(str('Enter your database name: '))
password = getpass.getpass("Enter your database password: ")

base_url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password=password,
    host="localhost",
    port=5432
)

create_database(base_url, db_name)

engine = create_engine(base_url.set(database=db_name))


df.to_sql(                  # Can be used sql to load, if dataset is much bigger
    'retail_records', 
    engine, 
    if_exists='replace'
)

Database 'retail' created successfully.

755

In [22]:
rfm_query = """
WITH cleaned AS (
    SELECT 
        customer_id,
        invoice,
        CAST(invoice_date AS TIMESTAMP) as invoice_date,
        quantity,
        price
    FROM public.retail_records
    WHERE quantity > 0
      AND price > 0
      AND customer_id IS NOT NULL
),
rfm_base AS (
    SELECT
        customer_id,
        MAX(invoice_date) AS last_purchase_date,
        COUNT(DISTINCT invoice) AS frequency,
        SUM(quantity * price) AS monetary
    FROM cleaned
    GROUP BY customer_id
)
SELECT
    customer_id,
    last_purchase_date,
    frequency,
    monetary,
    DATE_PART('day', (SELECT MAX(last_purchase_date) FROM rfm_base) - last_purchase_date) AS recency,
    NTILE(5) OVER (ORDER BY DATE_PART('day', (SELECT MAX(last_purchase_date) FROM rfm_base) - last_purchase_date) DESC) AS R_score,
    NTILE(5) OVER (ORDER BY frequency ASC) AS F_score,
    NTILE(5) OVER (ORDER BY monetary ASC) AS M_score
FROM rfm_base;
"""

with engine.connect() as conn:
    df_rfm = pd.read_sql(text(rfm_query), conn)

df_rfm

,customer_id,last_purchase_date,frequency,monetary,recency,r_score,f_score,m_score
0,17592,2009-12-01 10:49:00,1,148.30,738.0,1,1,1
1,14654,2009-12-01 12:57:00,1,246.86,737.0,1,1,1
2,15833,2009-12-02 11:59:00,1,80.40,737.0,1,1,1
3,17056,2009-12-01 12:55:00,1,128.60,737.0,1,1,1
4,17087,2009-12-02 10:41:00,1,221.53,737.0,1,1,1
...,...,...,...,...,...,...,...,...
5842,16401,2011-12-08 18:15:00,23,6847.45,0.0,5,5,5
5843,13113,2011-12-09 12:49:00,37,18230.07,0.0,5,5,5
5844,13102,2011-12-08 12:52:00,37,11380.10,0.0,5,5,5
5845,14051,2011-12-09 10:20:00,37,21755.98,0.0,5,5,5
5846,15311,2011-12-09 12:00:00,207,114581.87,0.0,5,5,5

In [23]:
pd_to_csv_path = os.path.join('..', 'data', '02_processed', 'rfm_retail.csv')

os.makedirs(os.path.dirname(pd_to_csv_path), exist_ok=True)
df_rfm.to_csv(pd_to_csv_path, index=False)

print(f"Saved to: {pd_to_csv_path}")

Saved to: ../data/02_processed/rfm_retail.csv